id = "codebabel-ztheme-dark"
name = "codebabel ztheme dark ğŸ”±"
version = "0.0.5"
schema_version = 1
authors = ["ğŸ‘¤ codebabel <codebabel.dev.contact@gmail.com>"]
description = "Description: ğŸ¡ codebabel ztheme dark and mirage themes."
repository = "https://github.com/codebabel-appbag/codebabel-ztheme-dark-source"